---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear
  namespace: myns
  labels:
    name: dov-bear
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dov-bear
  template:
    metadata:
      name: dov-bear
      labels:
        name: dov-bear
    spec:
      volumes:
      - name: config-vol
        configMap:
          name: config-cm
      - name: tmp-vol
        emptyDir: {}
      containers:
      - name: dov-bear
        image: chukmunnlee/dov-bear-golang:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: dov-bear
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 32Mi
            cpu: 100m
        volumeMounts:
        - name: config-vol
          mountPath: /app/config
          readOnly: true
        - name: tmp-vol
          mountPath: /opt/tmp
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear
  namespace: myns
  labels:
    name: dov-bear
spec:
  type: ClusterIP
  selector:
    name: dov-bear
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-hsvc
  namespace: myns
  labels:
    name: dov-bear-hsvc
spec:
  clusterIP: None
  selector:
    name: dov-bear
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-bear-hpa
  namespace: myns
  labels:
    name: dov-bear-hpa
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-bear
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: myns
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      name: dov-bear