---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: myns
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: myns
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306
---