apiVersion: v1
kind: Pod
metadata:
  name: dov-bear
  namespace: myns
  labels:
    name: dov-bear
spec:
  containers:
  - name: dov-bear
    image: chukmunnlee/dov-bear-golang:0.1
    imagePullPolicy: IfNotPresent
    env:
    - name: INSTANCE_NAME
      value: dov-bear
    - name: INSTANCE_HASH
      value: abc123
    ports:
    - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000